name: habitify_app
description: Mobile-only Habit Tracking app built with Flutter, Riverpod, Hive, and Firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  intl: ^0.19.0
  collection: ^1.18.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_messaging: ^15.1.0
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  fl_chart: ^0.68.0
  uuid: ^4.4.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
